"""add content generate related in skillpath

Revision ID: 53bbd96c8d24
Revises: af307a911ad0
Create Date: 2026-04-25 16:25:23.244959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53bbd96c8d24"
down_revision: Union[str, Sequence[str], None] = "af307a911ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skillpaths", sa.Column("practice_mode", sa.String(), nullable=True))
    op.add_column(
        "skillpaths", sa.Column("needs_examples", sa.Boolean(), nullable=True)
    )
    op.add_column("skillpaths", sa.Column("article_depth", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skillpaths", "article_depth")
    op.drop_column("skillpaths", "needs_examples")
    op.drop_column("skillpaths", "practice_mode")
    # ### end Alembic commands ###
