"""initial User, Goal, Learning, Roadmap schema

Revision ID: af307a911ad0
Revises:
Create Date: 2026-04-06 17:48:59.891721

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af307a911ad0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_outcome", sa.Text(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=False),
        sa.Column("criteria", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("constraints", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_goals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
        sa.UniqueConstraint("user_id", name=op.f("uq_goals_user_id")),
    )
    op.create_table(
        "learning_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("baseline_level", sa.String(), nullable=False),
        sa.Column("prior_knowledges", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("weak_areas", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("pace_preference", sa.String(), nullable=False),
        sa.Column("confidence_level", sa.String(), nullable=False),
        sa.Column("needs_recap", sa.Boolean(), nullable=False),
        sa.Column("prefers_examples_first", sa.Boolean(), nullable=False),
        sa.Column("overload_risk", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_learning_profiles_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_learning_profiles_user_id")),
    )
    op.create_table(
        "roadmaps",
        sa.Column("roadmap_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("target_outcome", sa.Text(), nullable=False),
        sa.Column("assumptions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_roadmaps_user_id_users")
        ),
        sa.PrimaryKeyConstraint("roadmap_id", name=op.f("pk_roadmaps")),
    )
    op.create_table(
        "milestones",
        sa.Column("milestone_id", sa.String(), nullable=False),
        sa.Column("roadmap_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("dependency_titles", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "prerequisite_milestone_ids", postgresql.ARRAY(sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("need_modification", sa.Boolean(), nullable=False),
        sa.Column("revision_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["roadmap_id"],
            ["roadmaps.roadmap_id"],
            name=op.f("fk_milestones_roadmap_id_roadmaps"),
        ),
        sa.PrimaryKeyConstraint("milestone_id", name=op.f("pk_milestones")),
    )
    op.create_table(
        "skillpaths",
        sa.Column("skillpath_id", sa.String(), nullable=False),
        sa.Column("milestone_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=False),
        sa.Column(
            "prerequisite_skillpath_ids", postgresql.ARRAY(sa.Text()), nullable=False
        ),
        sa.Column("learning_objectives", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("need_generation", sa.Boolean(), nullable=False),
        sa.Column("need_modification", sa.Boolean(), nullable=False),
        sa.Column("revision_reason", sa.Text(), nullable=True),
        sa.Column(
            "affected_downstream_ids", postgresql.ARRAY(sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.milestone_id"],
            name=op.f("fk_skillpaths_milestone_id_milestones"),
        ),
        sa.PrimaryKeyConstraint("skillpath_id", name=op.f("pk_skillpaths")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skillpaths")
    op.drop_table("milestones")
    op.drop_table("roadmaps")
    op.drop_table("learning_profiles")
    op.drop_table("goals")
    op.drop_table("users")
    # ### end Alembic commands ###
