"""remove redundant field

Revision ID: c4d952e2efa2
Revises: 53bbd96c8d24
Create Date: 2026-04-25 17:30:10.119006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4d952e2efa2"
down_revision: Union[str, Sequence[str], None] = "53bbd96c8d24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skillpaths", "article_depth")
    op.drop_column("skillpaths", "needs_examples")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skillpaths",
        sa.Column("needs_examples", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "skillpaths",
        sa.Column("article_depth", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
